using System;
using System.Net.Http;
using PTI.Autogenerated;
using PTI.Microservices.Generators.ConsoleConsumer.Models;

namespace PTI.Microservices.Generators.ConsoleConsumer
{
    class Program
    {
        static void Main(string[] args)
        {
            HttpClient httpClient = new HttpClient()
            {
                BaseAddress = new Uri("https://petstore.swagger.io/v2/")
            };
            SwaggerPetstore swaggerPetstore = new SwaggerPetstore();
            Models.GetInventoryResponseModel responseModel =
                swaggerPetstore.Getinventory<GetInventoryResponseModel>(httpClient).Result;
            Console.WriteLine($"Available: {responseModel.available}");
            Console.WriteLine("PRess any key to continue");
            Console.ReadKey();
        }
    }
}
